### ISSUE TITLE
LED addressing issues

### ISSUE THREAD

**Issue by friszky** [RaceFlightOne/RaceFlightOne#159]
It seems like the first LED on a strip will not respond, or act randomly. The others work totally fine and respond to inputs. 

LED one will either be off, or a random steady color, but *does* change color at random intervals.

This is on a Revolt V2, using Adafruit 8x RGB LED strip on PCB. Other strips exhibit same behavior. Changing the "LED Count" does not help.

**Comment by PGIII** [comment]
What version are you on ? and did it work on previous verisons ?

**Comment by friszky** [comment]
I'm now on rc18, previously on 299, and before that RC17. It didn't work on
any of them as far as i remember.

**Comment by PGIII** [comment]
I can recheck rc17 I'm pretty certain it worked then, I can replicate it on the later builds, I'll have to take a look

**Comment by charmlasse** [comment]
I have Revolt version 1 and other type of LED-board and I have noticed exactly the same issue. Worked fine with revolt195.bin, but not with revolt229.bin or revolt300.bin.

**Comment by proggod** [comment]
should be fixed in 402

**Comment by charmlasse** [comment]
Works fine now. Thanks!

Regards
Niklas



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: proggod <notifications@github.com>
Datum: 2017-11-21 17:54 (GMT+01:00)
Till: RaceFlightOne/RaceFlightOne <RaceFlightOne@noreply.github.com>
Kopia: charmlasse <moberg_niklas@hotmail.com>, Comment <comment@noreply.github.com>
Rubrik: Re: [RaceFlightOne/RaceFlightOne] LED addressing issues (#159)


should be fixed in 402
