### ISSUE TITLE
Custom quad layout

### ISSUE THREAD

**Issue by MarvFPV** [RaceFlightOne/RaceFlightOne#260]
I recently watched this video on youtube: https://www.youtube.com/watch?v=azhEtq4rWFc&t=396s (timestamp to important part)

Basically they guy was saying that when flying a stretch x quad, the pitch axis is faster than the roll axis even tho they have the same deg/s in the configurator. Because of that i went out flying yesterday and i noticed that the pitch axis was turning a slight bit faster, just as he said. Now there are 2 solutions to this "problem": First, you could just lower the pitch rates, but i find that a bit janky, and you wont get exactly the same rates on both axis. The second, more elegant solution betaflight has, is that you can create a custom quad layout for your frame, and then betaflight automatically does the rest. My idea would be that you would include an extra step to the RF1 wizard to insert your motor distance (1to2 and 2to3 for example) and the configurator now calculates a "stretch factor" (for example 1.2, so the frame is 1.2 long and 1 wide) and this factor will be included in the rates, so that we have the exact same speed on all axis.

I dont know how to write firmware for fcs, so if this is not possible, please tell me and i will close this.

Marvin

**Comment by proggod** [comment]
I am not sure how this could be possible, since we base the speed on the gyro.  The way the pid controller works is it sets a setpoint (which you set with radio) and then the pid controller tries to get to this set point as quick as possible.  I think it may feel faster due to the way the quad is shaped, but I doubt it actually is any faster.  Your best bet is to just change your rates, to make the feel the same.
