### ISSUE TITLE
Frsky s.port sensor lost warning

### ISSUE THREAD

**Issue by ankjaers** [RaceFlightOne/RaceFlightOne#96]
There seems to be a bug that causes my taranis to give a "sensor lost" warning very often. If I flash betaflight and enable telemetry this doesnt happen. It happens happens when the quad is in the air. But seems to happen more frequently when the remote is close to the quad. So it's likely not a bug. But it's surely something thats super annoying.

**Comment by deepimpactio** [comment]
Kalyn mentioned it would be adjusted in future builds. Appears packets are
being sent to fast for S.Port.

  Screenshot_20170425-062128.jpg
<https://drive.google.com/file/d/0ByVtmlwafXpKbDN0QUtyWmFnLVk/view?usp=drivesdk>



On Apr 25, 2017 5:13 AM, "ankjaers" <notifications@github.com> wrote:

There seems to be a bug that causes my taranis to give a "sensor lost"
warning very often. If I flash betaflight and enable telemetry this doesnt
happen. It happens happens when the quad is in the air. But seems to happen
more frequently when the remote is close to the quad. So it's likely not a
bug. But it's surely something thats super annoying.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RaceFlightOne/RaceFlightOne/issues/96>, or mute the
thread

**Comment by rs2k** [comment]
fixed in latest builds
